services:
  game_api:
    build: .
    ports: ['8080:8080']
    depends_on: [game_db]
  game_db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports: ['5432:5432']
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
