services:
  authDb:
    image: postgres:latest
    container_name: postgresAuth
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: authDb
        PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
     - "5433:5432"
    volumes:
     - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
       - net

  authCache:
    image: redis:latest
    container_name: redisAuth
    restart: always
    ports:
    - "6379:6379"
    networks:
       - net

  authService:
    image: auth
    build:
      context: .
      dockerfile: src/Services/AuthService.Dotnet/AuthService.Dotnet.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5050
      - ConnectionStrings__Postgres=Server=authDb;Port=5432;Database=authDb;User Id=postgres;Password=postgres;IncludeErrorDetail=true
      - ConnectionStrings__Redis=authCache:6379
    container_name: authService
    ports:
      - "5050:5050"
    depends_on:
      - authDb
      - authCache
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
       - net

networks:
  net:
    driver: bridge

volumes:
  pgdata:
    driver: local