services:
  game_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  game_service:
    build: src/Services/GameService.Nodejs
    ports: ["8080:8080"]
    depends_on: [game_db]

  leaderboard_db:
    image: mongo
    restart: always
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo_data:/data/db

  leaderboard_service:
    build: src/Services/LeaderboardService.Nodejs
    ports: ["8080:8081"]
    depends_on: [leaderboard_db]

  match_service:
    build: src/Services/MatchService.Nodejs
    ports: ["8080:8082"]

volumes:
  pgdata:
  mongo_data:
