services:
  leaderboard_api:
    build: .
    ports: ['8080:8080']
    depends_on: [leaderboard_db]
  leaderboard_db:
    image: mongo
    restart: always
    ports: ['27017:27017']
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
